name: Build and Deploy React Native APK

on:
  push:
    branches:
      - shaun
      - neo
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build the React Native project
        run: npm run android:build

      - name: Create APK
        run: npm run android:generate-apk

      - name: Upload APK artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk
